@main
struct ConfigurationResponseTests {
  static func main() {
    testConfigurationLoadingState()
    var snapshots = ConfigurationSnapshotBuffer<String>()
    let first = snapshots.beginRequest()
    let second = snapshots.beginRequest()
    snapshots.receive(revision: 1, value: "first edit")
    snapshots.completeRequest(first)
    precondition(snapshots.takeReadySnapshot() == nil, "Do not overwrite an unacknowledged UI edit")
    snapshots.receive(revision: 3, value: "latest edit")
    snapshots.receive(revision: 2, value: "older callback delivered late")
    snapshots.completeRequest(second)
    precondition(snapshots.takeReadySnapshot() == "latest edit")
    snapshots.receive(revision: 1, value: "stale")
    precondition(snapshots.takeReadySnapshot() == nil)

    let stoppedRequest = snapshots.beginRequest()
    snapshots.receive(revision: 4, value: "before stop")
    snapshots.reset()
    let newRequest = snapshots.beginRequest()
    snapshots.completeRequest(stoppedRequest)
    snapshots.receive(revision: 5, value: "after restart")
    precondition(
      snapshots.takeReadySnapshot() == nil, "Old completions must not acknowledge new requests")
    snapshots.completeRequest(newRequest)
    precondition(snapshots.takeReadySnapshot() == "after restart")
    snapshots.reset(through: 10)
    snapshots.receive(revision: 9, value: "notification delivered after stop")
    precondition(snapshots.takeReadySnapshot() == nil)
    snapshots.receive(revision: 11, value: "new session")
    precondition(snapshots.takeReadySnapshot() == "new session")
    precondition(!snapshots.reset(through: 10), "A delayed stop must not clear the new session")
    let pending = snapshots.beginRequest()
    snapshots.receive(revision: 12, value: "newer buffered session")
    precondition(!snapshots.reset(through: 11))
    snapshots.completeRequest(pending)
    precondition(snapshots.takeReadySnapshot() == "newer buffered session")
    var availability = ConfigurationSnapshotBuffer<String?>()
    let edit = availability.beginRequest()
    availability.receive(revision: 20, value: "edited settings")
    availability.receive(revision: 21, value: nil)  // Configuration failed to load.
    availability.receive(revision: 20, value: "late edit response")
    availability.completeRequest(edit)
    guard case .some(.none) = availability.takeReadySnapshot() else {
      preconditionFailure("A late response must not restore settings after a load error")
    }
    availability.receive(revision: 22, value: "recovered settings")
    precondition(availability.takeReadySnapshot()! == "recovered settings")
    var structure = ConfigurationSnapshotBuffer<[String]>()
    let olderEdit = structure.beginRequest()
    let deletion = structure.beginRequest(blocksEditing: true)
    precondition(
      structure.isEditingBlocked, "Block the second deletion before its index becomes stale")
    structure.receive(revision: 2, value: ["B", "C"])
    structure.completeRequest(deletion)
    precondition(structure.takeReadySnapshot() == nil)
    precondition(
      structure.isEditingBlocked, "Keep controls disabled while an older response is pending")
    structure.receive(revision: 1, value: ["A", "B", "C"])
    structure.completeRequest(olderEdit)
    precondition(structure.isEditingBlocked, "Acknowledgement alone must not enable stale controls")
    precondition(structure.takeReadySnapshot() == ["B", "C"])
    precondition(!structure.isEditingBlocked)
    let failed = structure.beginRequest(blocksEditing: true)
    structure.completeRequest(failed)
    precondition(structure.takeReadySnapshot() == nil)
    precondition(!structure.isEditingBlocked, "A rejected command must not leave controls disabled")
    _ = structure.beginRequest(blocksEditing: true)
    structure.reset()
    precondition(!structure.isEditingBlocked, "Stopping components must release the gate")
    print("Configuration response tests passed")
  }
}
