all:
	bash ../../scripts/create-icns.sh exported/KarabinerElements.png
	mv app.icns exported/KarabinerElements.icns
# Copy files
	cp    exported/KarabinerElements.icns    ../../../../src/apps/share/Resources/icons/001-KarabinerElements.icns
	cp    exported/KarabinerElements.png     ../../../../src/apps/share/Resources/icons/001-KarabinerElements.png
