∑.PHONY: build_make
build_make: build_vendor
	mkdir -p build \
		&& cd build \
		&& cmake .. \
		&& make -j4

.PHONY: clean_builds
clean_builds:
	rm -rf build

.PHONY: build_vendor
build_vendor:
	$(MAKE) -C $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/../../vendor build
