.PHONY: build_make
build_make:
	make -C ../../lib/test_runner
	mkdir -p build \
		&& cd build \
		&& cmake .. \
		&& make -j4

.PHONY: build_xcode
build_xcode:
	make -C ../../lib/test_runner
	mkdir -p build_xcode \
		&& cd build_xcode \
		&& cmake -G Xcode .. \
		&& xcodebuild -configuration Release SYMROOT="$(CURDIR)/build_xcode/build"

.PHONY: clean_builds
clean_builds:
	rm -rf build build_xcode
