name: Karabiner-Console-User-Server

targets:
  Karabiner-Console-User-Server:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-Console-User-Server
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
        - ../../../vendor/duktape-src
        - ../../../vendor/duktape-2.7.0/extras/console
        - ../../../vendor/duktape-2.7.0/extras/module-node
      OTHER_LDFLAGS:
        - ../../../vendor/duktape-src/build/Release/libduktape.a
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER: swift/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
        - ../../../vendor/vendor/include
      DEAD_CODE_STRIPPING: 'YES'
      SWIFT_VERSION: '6.0'
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++23'
      - path: swift
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../../apps/share/swift/KarabinerAppHelper.swift
      - path: ../../apps/share/swift/Views/MouseInsideModifier.swift
      - path: ../../apps/share/swift/Views/View+Extensions.swift
      - path: ../../../vendor/vendor/src/pqrs/osx/process_info
      - path: ../../../vendor/vendor/src/pqrs/osx/workspace
      - path: ../../apps/share/Resources/app.icns
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
    dependencies:
      - sdk: Carbon.framework
