all:
	$(MAKE) -C apps/PreferencesWindow
	$(MAKE) -C core/console_user_server
	$(MAKE) -C core/grabber

clean:
	$(MAKE) -C apps/PreferencesWindow clean
	$(MAKE) -C core/console_user_server clean
	$(MAKE) -C core/grabber clean
