all:
	bash ../../scripts/create-icns.sh exported/MultitouchExtension.png
	mv app.icns exported/MultitouchExtension.icns
# Copy files
	cp    exported/MultitouchExtension.icns    ../../../../src/apps/MultitouchExtension/Resources/app.icns
	cp    exported/MultitouchExtension.icns    ../../../../src/apps/share/Resources/icons/000-MultitouchExtension.icns
	cp    exported/MultitouchExtension.png     ../../../../src/apps/share/Resources/icons/000-MultitouchExtension.png
