name: Karabiner-Core-Service

targets:
  Karabiner-Core-Service:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-Core-Service
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
        - ../../../vendor/duktape-src
        - ../../../vendor/duktape-2.7.0/extras/console
        - ../../../vendor/duktape-2.7.0/extras/module-node
      OTHER_LDFLAGS:
        - ../../../vendor/duktape-src/build/Release/libduktape.a
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER: swift/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
        - ../../../vendor/vendor/include
      DEAD_CODE_STRIPPING: 'YES'
    # It needs to be built as an application rather than a tool in order to appear in the Input Monitoring list in System Settings.
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../../vendor/vendor/src/pqrs/osx/process_info
      - path: ../../../vendor/vendor/src/pqrs/osx/workspace
      - path: Resources
        excludes:
          - .gitignore
          - '*.orig.png'
          - '*.plist.in'
      - path: ../../apps/share/Resources/app.icns
