all:
	make -C ../lib/KarabinerKit
	make build_xcode

clean: clean_builds

run:
	./build_xcode/build/Release/Karabiner-NotificationWindow.app/Contents/MacOS/Karabiner-NotificationWindow

include ../../Makefile.rules
