all:
	$(MAKE) -C cg_event_set_flags
	$(MAKE) -C cg_post_event
	$(MAKE) -C codesign
	$(MAKE) -C control_led
	$(MAKE) -C dump_caps_lock_state
	$(MAKE) -C dump_constants
	$(MAKE) -C dump_hid_report
	$(MAKE) -C dump_hid_value
	$(MAKE) -C dump_libkrbn
	$(MAKE) -C dump_system_preferences
	$(MAKE) -C eventtap
	$(MAKE) -C front_application_observer
	$(MAKE) -C iopmlib
	$(MAKE) -C session
	$(MAKE) -C version_monitor
	$(MAKE) -C virtual_device_client

clean:
	$(MAKE) -C cg_event_set_flags clean
	$(MAKE) -C cg_post_event clean
	$(MAKE) -C codesign clean
	$(MAKE) -C control_led clean
	$(MAKE) -C dump_caps_lock_state clean
	$(MAKE) -C dump_constants clean
	$(MAKE) -C dump_hid_report clean
	$(MAKE) -C dump_hid_value clean
	$(MAKE) -C dump_libkrbn clean
	$(MAKE) -C dump_system_preferences clean
	$(MAKE) -C eventtap clean
	$(MAKE) -C front_application_observer clean
	$(MAKE) -C iopmlib clean
	$(MAKE) -C session clean
	$(MAKE) -C version_monitor clean
	$(MAKE) -C virtual_device_client clean
