all:
	$(MAKE) -C eventtap
	$(MAKE) -C dump_hid_report
	$(MAKE) -C dump_system_preferences

clean:
	$(MAKE) -C eventtap clean
	$(MAKE) -C dump_hid_report clean
	$(MAKE) -C dump_system_preferences clean
