all: build_make
	./build/karabiner_test
	rmdir mkdir_example/a/b/c/d/e
	rmdir mkdir_example/a/b/c/d
	rmdir mkdir_example/a/b/c
	rmdir mkdir_example/a/b
	rmdir mkdir_example/a
	rmdir mkdir_example

clean: clean_builds

include ../../../src/Makefile.rules
