all:
	$(MAKE) -C apps/AppIconSwitcher
	$(MAKE) -C apps/EventViewer
	$(MAKE) -C apps/MultitouchExtension
	$(MAKE) -C apps/ServiceManager-Non-Privileged-Agents
	$(MAKE) -C apps/ServiceManager-Privileged-Daemons
	$(MAKE) -C apps/SettingsWindow
	$(MAKE) -C apps/Updater
	$(MAKE) -C bin/cli
	$(MAKE) -C apps/ConsoleUserServer
	$(MAKE) -C apps/CoreService
	$(MAKE) -C lib/libkrbn

clean:
	$(MAKE) -C apps/AppIconSwitcher clean
	$(MAKE) -C apps/EventViewer clean
	$(MAKE) -C apps/MultitouchExtension clean
	$(MAKE) -C apps/ServiceManager-Non-Privileged-Agents clean
	$(MAKE) -C apps/ServiceManager-Privileged-Daemons clean
	$(MAKE) -C apps/SettingsWindow clean
	$(MAKE) -C apps/Updater clean
	$(MAKE) -C bin/cli clean
	$(MAKE) -C apps/ConsoleUserServer clean
	$(MAKE) -C apps/CoreService clean
	$(MAKE) -C lib/libkrbn clean
