all:
	$(MAKE) -C apps/EventViewer
	$(MAKE) -C apps/PreferencesWindow
	$(MAKE) -C apps/Updater
	$(MAKE) -C core/console_user_server
	$(MAKE) -C core/event_dispatcher
	$(MAKE) -C core/grabber
	$(MAKE) -C core/kext/VirtualHIDDevice

clean:
	$(MAKE) -C apps/EventViewer clean
	$(MAKE) -C apps/PreferencesWindow clean
	$(MAKE) -C apps/Updater clean
	$(MAKE) -C core/console_user_server clean
	$(MAKE) -C core/event_dispatcher clean
	$(MAKE) -C core/grabber clean
	$(MAKE) -C core/kext/VirtualHIDDevice clean
