all:
	$(MAKE) -C apps/EventViewer
	$(MAKE) -C apps/Menu
	$(MAKE) -C apps/MultitouchExtension
	$(MAKE) -C apps/NotificationWindow
	$(MAKE) -C apps/PreferencesWindow
	$(MAKE) -C apps/Updater
	$(MAKE) -C apps/lib/KarabinerKit
	$(MAKE) -C bin/cli
	$(MAKE) -C core/console_user_server
	$(MAKE) -C core/grabber
	$(MAKE) -C core/kextd
	$(MAKE) -C core/observer
	$(MAKE) -C core/session_monitor
	$(MAKE) -C lib/libkrbn

clean:
	$(MAKE) -C apps/EventViewer clean
	$(MAKE) -C apps/Menu clean
	$(MAKE) -C apps/MultitouchExtension clean
	$(MAKE) -C apps/NotificationWindow clean
	$(MAKE) -C apps/PreferencesWindow clean
	$(MAKE) -C apps/Updater clean
	$(MAKE) -C apps/lib/KarabinerKit clean
	$(MAKE) -C bin/cli clean
	$(MAKE) -C core/console_user_server clean
	$(MAKE) -C core/grabber clean
	$(MAKE) -C core/kextd clean
	$(MAKE) -C core/observer clean
	$(MAKE) -C core/session_monitor clean
	$(MAKE) -C lib/libkrbn clean
