.PHONY: build_make
build_make:
	mkdir -p build \
		&& cd build \
		&& cmake .. \
		&& make

.PHONY: build_xcode
build_xcode:
	mkdir -p build_xcode \
		&& cd build_xcode \
		&& cmake -G Xcode .. \
		&& xcodebuild -configuration Release SYMROOT="$(CURDIR)/build"

.PHONY: clean_builds
clean_builds:
	rm -rf build build_xcode
