name: karabiner_cli

targets:
  karabiner_cli:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - ../../share
        - ../../../vendor/duktape-src
        - ../../../vendor/duktape-2.7.0/extras/console
        - ../../../vendor/duktape-2.7.0/extras/module-node
      OTHER_LDFLAGS:
        - ../../../vendor/duktape-src/build/Release/libduktape.a
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER:
        - src/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
        - ../../../vendor/vendor/include
      DEAD_CODE_STRIPPING: 'YES'
    type: tool
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../../vendor/vendor/src/pqrs/osx/process_info
      - path: ../../../vendor/vendor/src/pqrs/osx/workspace
