name: karabiner_cli

targets:
  karabiner_cli:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - ../../share
        - ../../vendor/duktape-2.7.0/src
        - ../../vendor/duktape-2.7.0/extras/console
        - ../../vendor/duktape-2.7.0/extras/module-node
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER:
        - ../../vendor/cget/include/pqrs/osx/process_info/impl/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
        - ../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
    type: tool
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../vendor/duktape-2.7.0/src/duktape.c
      - path: ../../vendor/duktape-2.7.0/extras/console/duk_console.c
      - path: ../../vendor/duktape-2.7.0/extras/module-node/duk_module_node.c
      - path: ../../vendor/cget/src/pqrs/osx/process_info
