#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

#
# Set suid
#

chmod 4755 '/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_session_monitor'

#
# Register /Applications/Karabiner-Elements.app in the Launch Services database.
#

'/Library/Application Support/org.pqrs/Karabiner-Elements/Karabiner-Elements-Services.app/Contents/MacOS/Karabiner-Elements-Services' register-core

#
# Relaunch karabiner processes
#

killall karabiner_grabber
killall karabiner_session_monitor
killall karabiner_console_user_server
killall Karabiner-NotificationWindow

#
# Update version file
#

cp \
    '/Library/Application Support/org.pqrs/Karabiner-Elements/package-version' \
    '/Library/Application Support/org.pqrs/Karabiner-Elements/version'

#
# Create a backup to allow recovery if the user manually deletes Karabiner-Elements without using the uninstaller
#

tar -C /Applications -cf '/Library/Application Support/org.pqrs/Karabiner-Elements/Karabiner-Elements.app.tar.gz' Karabiner-Elements.app

exit 0
