#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

uninstall_script='/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall_core.sh'
if [ -f "$uninstall_script" ]; then
    sh "$uninstall_script"
fi

exit 0
