#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ----------------------------------------
# unload before install

launchctl unload /Library/LaunchDaemons/org.pqrs.Karabiner-Elements.plist

kextunload -b org.pqrs.driver.VirtualHIDManager
kextunload -b org.pqrs.driver.VirtualHIDKeyboard
kextunload -b org.pqrs.driver.VirtualHIDPointing

# ----------------------------------------
# uninstall
rm -f  '/Library/LaunchDaemons/org.pqrs.Karabiner-Elements.plist'
rm -rf '/Library/Application Support/org.pqrs/Karabiner-Elements'
rm -rf '/Library/Extensions/org.pqrs.driver.VirtualHIDKeyboard.kext'
rm -rf '/Library/Extensions/org.pqrs.driver.VirtualHIDManager.kext'
rm -rf '/Library/Extensions/org.pqrs.driver.VirtualHIDPointing.kext'

exit 0
