name: Tests

on:
  push:
    paths-ignore:
      - vendor/cpm-cmake-package-lock
  pull_request:
    paths-ignore:
      - vendor/cpm-cmake-package-lock
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-15
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Select Xcode 26 if available
        run: |
          if [ -d /Applications/Xcode_26.0.app ]; then
            sudo xcode-select -s /Applications/Xcode_26.0.app
          fi
          xcodebuild -version

      - name: Install dependencies
        run: brew install cmake xcodegen

      - name: Run tests
        run: ruby scripts/reduce-logs.rb 'make -C tests'
