all:
	bash ../../scripts/create-icns.sh exported/EventViewer.png
	mv app.icns exported/EventViewer.icns
# Copy files
	cp    exported/EventViewer.icns    ../../../../src/apps/share/Resources/icons/001-EventViewer.icns
	cp    exported/EventViewer.png     ../../../../src/apps/share/Resources/icons/001-EventViewer.png
